export const BASE_URL = 'http://localhost:3000/api';

export const PURCHASE_COLUMN_KEYS = [
  'entryNumber',
  'status',
  'lastStatusChangedAt',
  'site',
  'contractSubject',
  'supplierName',
  'smp',
  'supplierInn',
  'initialPrice',
  'purchaseAmount',
  'contractNumber',
  'contractDate',
  'validFrom',
  'validTo',
  'contractEnd',
  'placementDate',
  'methodOfPurchase',
  'documentNumber',
  'completed',
  'savings',
  'performanceAmount',
  'performanceForm',
  'additionalAgreementNumber',
  'currentContractAmount',
  'remainingContractAmount',
  'bankGuaranteeValidFrom',
  'bankGuaranteeValidTo',
  'publication',
  'responsible',
  'planNumber',
  'applicationAmount',
  'comment',
  'actions',
];
